version: "3"
services:
  front:
    build: ./frontend
    tty: true
    volumes:
      - ./frontend:/frontend
      - .bash_history:/home/node/.bash_history
    ports:
      - "8080:8080"
    user: node
    command: sh -c "cd app && yarn serve"
  api:
    build: ./api
    tty: true
    volumes:
      - ./api:/var/www/app/
      - .bash_history:/home/node/.bash_history
    ports:
      - "3000:3000"
    user: node
    command: sh -c "yarn run dev"