<template>
  <div>
    <h2>Users</h2>
    <nav>
      <router-link 
        to="/" 
        active-class="link--active"
        exact
        class="link"
      >Home</router-link>
      <router-link 
        to="/users" 
        active-class="link--active"
        class="link"
      >Users</router-link>
    </nav>
  </div>
</template>
